### ISSUE TITLE
Error in phaseblock flipping module

### ISSUE THREAD

**Issue by willhooper** [KolmogorovLab/Wakhan#4]
Hi,

I'm running into an error when trying to run Wakhan on a CRAM haplotagged with Longphase. 

Here's the command I used:
```
  python /Wakhan/src/main.py \
    --threads 32 \
    --reference GRCh38_full_analysis_set_plus_decoy_hla.fasta \
    --target-bam COLO829-T.10X.haplotagged.cram \
    --out-dir-plots $OUT_DIR \
    --phased-vcf COLO829-N.5X.PASS.phased_SNV_InDels.vcf.gz \
    --smoothing-enable True \
    --copynumbers-enable True  \
    --unphased-reads-coverage-enable True \
    --phaseblock-flipping-enable True  \
    --genome-name COLO829-T.10X \
    --cut-threshold 150 \
    --het-phased-snps-freq-enable True
```

And the full log output:
```
Parsing reads from COLO829-T.10X.haplotagged.cram
Parsed 2815448 segments
INFO:root:Computing coverage histogram
INFO:root:Computing coverage for bins
INFO:root:Writing coverage for bins
INFO:root:Parsing phaseblocks information
INFO:root:bcftools -> Filtering out hetrozygous and phased SNPs and generating a new VCF
INFO:root:bcftools -> Query for phasesets and GT, DP, VAF feilds by creating a CSV file
INFO:root:Computing coverage for phaseblocks
INFO:root:Writing coverage for phaseblocks
INFO:root:Loading coverage (bins) and coverage (phaseblocks) files...
INFO:root:Generating coverage plots chromosomes-wise
INFO:root:bcftools -> Query for het SNPs and creating a data/COLO829-N.5X.PASS.phased_SNV_InDels.vcf_het_snps.csv CSV file
INFO:root:SNPs frequency -> CSV to dataframe conversion
INFO:root:SNPs frequency -> Comuting het SNPs frequency from tumor BAM
[mpileup] 1 samples in 1 input files
...
[mpileup] 1 samples in 1 input files
INFO:root:Plots generation for chr1
INFO:root:phaseblock flipping module
INFO:root:smoothing module
INFO:root:hetrozygous phased snps frequencies coverage module
INFO:root:phaseblock flipping module
Traceback (most recent call last):
  File "/Wakhan/src/main.py", line 268, in <module>
    main()
  File "/Wakhan/src/main.py", line 227, in main
    coverage_plots_chromosomes(csv_df_coverage, csv_df_phasesets, arguments, thread_pool)
  File "/Wakhan/src/plots.py", line 218, in coverage_plots_chromosomes
    phaseblock_flipping(is_simple_correction, snps_haplotype1_mean, snps_haplotype2_mean,
  File "/Wakhan/src/phasing_correction.py", line 96, in phaseblock_flipping
    max_value_index = diff.index(max(diff))
ValueError: max() arg is an empty sequence
```

The intermediate files I see are:
```
coverage.csv
COLO829-N.5X.PASS.phased_SNV_InDels.vcf_phasesets.csv
coverage_ps.csv
COLO829-N.5X.PASS.phased_SNV_InDels.vcf_het_snps.bed
COLO829-T.10X.haplotagged_reduced.bam
COLO829-N.5X.PASS.phased_SNV_InDels.vcf_het_phased_snps.vcf.gz
COLO829-N.5X.PASS.phased_SNV_InDels.vcf_het_snps.csv
*.bed
*_SNPs.csv
COLO829-T.10X_SNPs.csv
COLO829-N.5X.PASS.phased_SNV_InDels.vcf_het_snps_freqs.csv
snps_frequencies.csv
```
None of the files are empty except `coverage_ps.csv`

Do you have any insight as to what's going on here? Thanks in advance for your help! 

Best,
Will

**Comment by tahashmi** [comment]
Hi, Thanks for reporting it. This issue is because of empty `coverage_ps.csv`. One reason of this file being empty could be that all phaseblocks are less than 50k (we are removing those if smaller than by default `bin_size` = 50k). 

An alternative to this is using simple heuristics for phase correction (Wakhan will just assign higher values to hp1 and lower values to hp2):
Could you place this below condition in `plots.py` at line [216 ](https://github.com/KolmogorovLab/Wakhan/blob/dd8d979744c6afde96ee45adbd2f556b172c11a3/src/plots.py#L216) to test it if it works.
 
```
if len(ref_start_values_phasesets) < 5:
    is_simple_correction = True
```

**Comment by tahashmi** [comment]
I have updated the code in main repo for this issue. If you still face this issue please reopen it. Thanks!
